show databases;
create database Facebook;
use Facebook;
create table User(usr_id int,usr_name varchar(25),age int ,gender char,ins_time datetime DEFAULT NOW(),primary key (usr_id));
create table Post(p_id int,usr_id int,p_name varchar(25),p_time datetime default CURRENT_TIMESTAMP,constraint post primary key(p_id,usr_id),foreign key (usr_id) references User(usr_id));
create table Likepost(l_id int, p_id int,usr_id int,cur_time datetime default CURRENT_TIMESTAMP, constraint like_post primary key (l_id,p_id,usr_id), constraint like_foreign foreign key (p_id,usr_id) references Post(p_id,usr_id));
create table Comment(cmnt_usr_id int not null,cmnt_id int ,p_id int not null,usr_id int not null,comment  varchar(50),constraint comm_foreign foreign key (p_id,usr_id)  references Post(p_id,usr_id));
create table Share(s_uid int not null,p_id int not null,usr_id int not null, constraint share_foreign foreign key(p_id,usr_id) references Post(p_id,usr_id), constraint share_user foreign key(s_uid) references User(usr_id));
insert into User (usr_id,usr_name,age,gender) values(1,"mathi",22,'M');
insert into User (usr_id,usr_name,age,gender) values(2,"raghu",22,'M');
insert into User (usr_id,usr_name,age,gender) values(3,"tamilarasan",22,'M');
insert into User (usr_id,usr_name,age,gender) values(4,"prabakaran",22,'M');
insert into User (usr_id,usr_name,age,gender) values(5,"ajees",22,'M');
insert into User (usr_id,usr_name,age,gender) values(6,"eliyas",22,'M');
insert into User (usr_id,usr_name,age,gender) values(7,"muthupandi",22,'M');
insert into User (usr_id,usr_name,age,gender) values(8,"kowsika",22,'F');
insert into User (usr_id,usr_name,age,gender) values(9,"kiruthiga",20,'F');
insert into User (usr_id,usr_name,age,gender) values(9,"gayathri",20,'F');
insert into User (usr_id,usr_name,age,gender) values(10,"soumiya",20,'F');
insert into User (usr_id,usr_name,age,gender) values(11,"gayathri",20,'F');
insert into Post(p_id,usr_id,p_name) values (100,1,"photo1");
insert into Post(p_id,usr_id,p_name) values (100,12,"photo1");
insert into Post(p_id,usr_id,p_name) values (100,1,"photo1");
insert into Post(p_id,usr_id,p_name) values (100,2,"photo1");
insert into Post(p_id,usr_id,p_name) values (101,3,"photo1");
insert into Likepost (l_id,p_id,usr_id) values (5,100,1);
insert into Likepost (l_id,p_id,usr_id) values (5,100,2);
insert into Comment(cmnt_usr_id,p_id,usr_id,comment)values(7,100,1,"i likes ur photo");
alter table Comment add column cmttime datetime default CURRENT_TIMESTAMP;
insert into Comment(cmnt_usr_id,p_id,usr_id,comment)values(1,100,1,"ok thanks da");
insert into Comment(cmnt_usr_id,p_id,usr_id,comment)values(7,100,1,"update profile da");
insert into Post(P_id,usr_id,p_name)values(25,5,"profile");
insert into Post(P_id,usr_id,p_name)values(55,2,"profile");
insert into Post(P_id,usr_id,p_name)values(53,1,"profile");
insert into Post(P_id,usr_id,p_name)values(3,1,"status");
insert into Post(p_id,usr_id,p_name)values(123,5,"anyqueries");
insert into Post(p_id,usr_id,p_name)values(143,7,"statuschanged");
insert into Post(p_id,usr_id,p_name)values(143,9,"changephoto");
insert into Post(p_id,usr_id,p_name)values(134,10,"photoupdate");
insert into Post(p_id,usr_id,p_name)values(124,2,"nameupdate");
insert into Post(p_id,usr_id,p_name)values(504,8,"profilepic");
alter table Comment drop column cmnt_id;
create table Share like Comment;
insert into Post(p_id,usr_id,p_name)values(101,3,"sharephoto");
insert into Post(p_id,usr_id,p_name)values(101,4,"sharephoto");
insert into Post(p_id,usr_id,p_name)values(101,5,"sharestatus");
insert into Post(p_id,usr_id,p_name)values(103,5,"sharephoto");
insert into Post(p_id,usr_id,p_name)values(100,9,"sharephoto");
insert into Post(p_id,usr_id,p_name)values(103,1,"sharephoto");
insert into Post(p_id,usr_id,p_name)values(103,2,"sharepic");
insert into comment(cmnt_usr_id,p_id,usr_id,comment)values(1,101,3,"nicepic");
insert into comment(cmnt_usr_id,p_id,usr_id,comment)values(10,101,3,"awesome");
insert into comment(cmnt_usr_id,p_id,usr_id,comment)values(5,101,3,"awesome");
insert into comment(cmnt_usr_id,p_id,usr_id,comment)values(4,101,3,"smiley");
insert into comment(cmnt_usr_id,p_id,usr_id,comment)values(4,101,4,"smiley");
insert into comment(cmnt_usr_id,p_id,usr_id,comment)values(4,101,5,"smiley");
insert into comment(cmnt_usr_id,p_id,usr_id,comment)values(3,101,5,"super");
insert into comment(cmnt_usr_id,p_id,usr_id,comment)values(1,101,5,"nice");
insert into comment(cmnt_usr_id,p_id,usr_id,comment)values(1,101,4,"nice");
insert into share(cmnt_usr_id,p_id,usr_id,comment)values(1,101,4,"nice");
insert into share(cmnt_usr_id,p_id,usr_id,comment)values(1,143,9,"nice");
insert into share(cmnt_usr_id,p_id,usr_id,comment)values(2,143,9,"nice");
insert into share(cmnt_usr_id,p_id,usr_id,comment)values(3,143,9,"nice");
insert into share(cmnt_usr_id,p_id,usr_id,comment)values(4,143,9,"nice");
insert into share(cmnt_usr_id,p_id,usr_id,comment)values(5,143,9,"nice");
insert into share(cmnt_usr_id,p_id,usr_id,comment)values(5,101,1,"nice");
insert into share(cmnt_usr_id,p_id,usr_id,comment)values(5,101,3,"nice");
insert into share(cmnt_usr_id,p_id,usr_id,comment)values(2,101,3,"nice");
insert into share(cmnt_usr_id,p_id,usr_id,comment)values(9,101,3,"nice");
insert into share(cmnt_usr_id,p_id,usr_id,comment)values(10,101,3,"nice");
insert into share(cmnt_usr_id,p_id,usr_id,comment)values(5,101,3,"nice");
insert into likepost(l_id,p_id,usr_id)values(10,101,3);
insert into likepost(l_id,p_id,usr_id)values(3,101,3);
insert into likepost(l_id,p_id,usr_id)values(4,101,3);
insert into likepost(l_id,p_id,usr_id)values(5,101,3);
insert into likepost(l_id,p_id,usr_id)values(6,101,3);
insert into likepost(l_id,p_id,usr_id)values(7,101,3);
insert into likepost(l_id,p_id,usr_id)values(1,101,4);
insert into likepost(l_id,p_id,usr_id)values(2,101,4);
insert into likepost(l_id,p_id,usr_id)values(3,101,4);
insert into likepost(l_id,p_id,usr_id)values(4,101,4);
insert into likepost(l_id,p_id,usr_id)values(5,101,4);
insert into likepost(l_id,p_id,usr_id)values(9,101,4);
insert into likepost(l_id,p_id,usr_id)values(10,101,4);
insert into likepost(l_id,p_id,usr_id)values(11,101,4);
insert into likepost(l_id,p_id,usr_id)values(11,101,5);
insert into likepost(l_id,p_id,usr_id)values(10,101,5);
insert into likepost(l_id,p_id,usr_id)values(9,101,5);
insert into likepost(l_id,p_id,usr_id)values(8,101,5);
insert into likepost(l_id,p_id,usr_id)values(4,101,5);
select user.usr_name from user innerjoin Likepost on likepost.l_id=user.usr_id where likepost.usr_id=3 and likepost.p_id=101;
select user.usr_name from user inner join user.usr_id=likepost.usr_id;
select user.usr_name from user inner join likepost on user.usr_id=likepost.usr_id;
select user.usr_name from user inner join likepost on user.usr_id=likepost.l_id;
select user.usr_name from user inner join likepost on user.usr_id=likepost.l_id where likepost.p_id=101 and likepost.usr_id=3;
select user.usr_name,likepost.cur_time from user inner join likepost on user.usr_id=likepost.l_id where likepost.p_id=101 and likepost.usr_id=3 order by likepost.cur_time desc;
select * from facebook.tables;
select * from facebook.information_schema.tables;
show tables;
show tables in facebook;
exit
